### ISSUE TITLE
Include location parameter in the body example

### ISSUE THREAD

**Issue by lgbaeza** [GoogleCloudPlatform/workflows-demos#134]
https://github.com/GoogleCloudPlatform/workflows-demos/blob/4c4fbd91317f3a0293092d27b37eda1008403af0/bigquery-parallel/workflow-parallel.yaml#L44

Based on [QueryRequest Docs](https://cloud.google.com/workflows/docs/reference/googleapis/bigquery/v2/Overview#QueryRequest) and my tests, **location** atribute should be provided in the example for user convinience. It is not required, but it will be commonly required (e.g. customer using multi-regional datasets).

````yaml
body:
  location: us #See details at https://cloud.google.com/bigquery/docs/locations#specifying_your_location
  useLegacySql: false
  useQueryCache: false
  timeoutMs: 30000
  # Find top 100 titles with most views on Wikipedia
  query: ${
````
