### ISSUE TITLE
Sample: Workflows calling gcloud commands

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/workflows-demos#73]
Take Kris' sample and generalize it

**Comment by glaforge** [comment]
Example from Kris:
```yaml
main:
    params: [input]
    steps:
    - list_workflows:
        call: gcloud
        args:
            args: "workflows list"
        result: r
    - done:
        return: ${r}

gcloud:
    params: [args]
    steps:
    - gcloud:
        call: googleapis.cloudbuild.v1.projects.builds.create
        args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            parent: ${"projects/" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + "/locations/global"}
            body:
                serviceAccount: ${sys.get_env("GOOGLE_CLOUD_SERVICE_ACCOUNT_NAME")}
                options:
                    logging: CLOUD_LOGGING_ONLY
                steps:
                - name: [gcr.io/google.com/cloudsdktool/cloud-sdk](http://gcr.io/google.com/cloudsdktool/cloud-sdk)
                  entrypoint: /bin/bash
                  # TODO: Should use $BUILDER_OUTPUT for "/builder/ouputs", but couldn't get substitution to work
                  args: ${["-c", "gcloud " + args + " > /builder/outputs/output"]}
        result: r
    - return:
        return: ${text.decode(base64.decode(r.metadata.build.results.buildStepOutputs[0]))}
```
